# -----------------------------
# 端口 port:
# -----------------------------
# http: 8000
# -----------------------------
# 挂载卷 volumes:
# -----------------------------
# ./data -> /app/data
# -----------------------------

networks:
  npm-network:
    external: true

services:
  hasty-paste:
    image: ghcr.io/enchant97/hasty-paste:latest
    container_name: hasty-paste
    restart: unless-stopped
    networks:
      - npm-network
    # ports:
    #   - 8000:8000
    volumes:
      - ./data:/app/data

