services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    network_mode: "host"
    command: tunnel run
    environment:
      - "TUNNEL_TOKEN=${TUNNEL_TOKEN:?TUNNEL_TOKEN required}"
